version: '3'

# Глобальные переменные проекта

vars:
  GO_VERSION: '1.23.0'
  GOLANGCI_LINT_VERSION: 'v2.1.5'
  GCI_VERSION: 'v0.13.6'
  GOFUMPT_VERSION: 'v0.8.0'
  BUF_VERSION: '1.64.0'
  PROTOC_GEN_GO_VERSION: 'v1.36.6'
  PROTOC_GEN_GO_GRPC_VERSION: 'v1.5.1'
  OGEN_VERSION: 'v1.14.0'
  YQ_VERSION: 'v4.45.2'

  BIN_DIR: '{{.ROOT_DIR}}/bin'
  GOLANGCI_LINT: '{{.BIN_DIR}}/golangci-lint'
  GCI: '{{.BIN_DIR}}/gci'
  GOFUMPT: '{{.BIN_DIR}}/gofumpt'
  BUF: '{{.BIN_DIR}}/buf'
  PROTOC_GEN_GO: '{{.BIN_DIR}}/protoc-v1-go'
  PROTOC_GEN_GO_GRPC: '{{.BIN_DIR}}/protoc-v1-go-grpc'
  OGEN: '{{.BIN_DIR}}/ogen'
  YQ: '{{.BIN_DIR}}/yq'

  NODE_MODULES_DIR: '{{.ROOT_DIR}}/node_modules/.bin'
  REDOCLY: '{{.NODE_MODULES_DIR}}/redocly'

  OPEN_API_ORDER_V1_BASE: '{{.ROOT_DIR}}/shared/api/order/v1/order.openapi.yaml'
  OPEN_API_ORDER_V1_BUNDLE: '{{.ROOT_DIR}}/shared/api/bundles/order.openapi.v1.bundle.yaml'
  OPEN_API_FILES: '{{.ROOT_DIR}}/shared/api/bundles'

  API_BUNDLE: shared\api\bundle\order.openapi.v1.bundle.yaml
  API_TARGET: shared\pkg\api\order\v1

  MODULES: inventory shared payment order

tasks:
  install-formatters:
    desc: "Устанавливает форматтеры gci и gofumpt в ./bin"
    summary: |
      Эта задача проверяет наличие инструментов форматирования кода gofumpt и gci в директории bin.
      Если инструменты не найдены, они будут автоматически установлены с указанными версиями.

      Используется:
        - gofumpt: для форматирования кода Go
        - gci: для сортировки импортов Go
    cmds:
      - |
        [ -f {{.GOFUMPT}} ] || {
          echo '📦 Устанавливаем gofumpt {{.GOFUMPT_VERSION}}...'
          GOBIN={{.BIN_DIR}} go install mvdan.cc/gofumpt@{{.GOFUMPT_VERSION}}
        }
        [ -f {{.GCI}} ] || {
          echo '📦 Устанавливаем gci {{.GCI_VERSION}}...'
          GOBIN={{.BIN_DIR}} go install github.com/daixiang0/gci@{{.GCI_VERSION}}
        }
    status:
      - test -x {{.GOFUMPT}}
      - test -x {{.GCI}}

  format:
    desc: "Форматирует весь проект gofumpt + gci, исключая mocks"
    summary: |
      Форматирует все Go-файлы проекта с использованием gofumpt для стандартизации кода
      и gci для сортировки импортов, исключая файлы в директориях mocks.

      Использует инструменты:
        - gofumpt: для стандартизации форматирования
        - gci: для сортировки импортов по стандартным группам
    #deps: [ install-formatters ]
    cmds:
      - |
        echo "🧼 Форматируем через gofumpt ..."

        for module in {{.MODULES}}; do
          if [ -d "$module" ]; then
            echo "🧼 Форматируем $module"
            find $module -type f -name '*.go' ! -path '*/mocks/*' -exec {{.GOFUMPT}} -extra -w {} +
          fi
        done
      - |
        echo "🎯 Сортируем импорты через gci ..."

        for module in {{.MODULES}}; do
          if [ -d "$module" ]; then
            echo "🎯 Сортируем импорты в $module"
            find $module -type f -name '*.go' ! -path '*/mocks/*' -exec {{.GCI}} write -s standard -s default -s "prefix(github.com/olezhek28/microservices-course-olezhek-solution)" {} +
          fi
        done

  install-golangci-lint:
    desc: "Устанавливает golangci-lint в каталог bin"
    summary: |
      Проверяет наличие golangci-lint в директории bin.
      Если инструмент не найден, автоматически устанавливает его через go install.

      Устанавливаемая версия: {{.GOLANGCI_LINT_VERSION}}
    cmds:
      - |
        [ -f {{.GOLANGCI_LINT}} ] || {
          install -d {{.BIN_DIR}} || true  # вместо mkdir -p
          echo "📦 Устанавливаем golangci-lint {{.GOLANGCI_LINT_VERSION}}..."
          GOBIN={{.BIN_DIR}} go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@{{.GOLANGCI_LINT_VERSION}}
        }
    status:
      - test -x {{.GOLANGCI_LINT}}

  lint:
    desc: "Запускает golangci-lint для всех модулей"
    summary: |
      Запускает линтер golangci-lint для всех модулей проекта.
      Линтер проверяет код на соответствие стандартам качества и лучшим практикам.
      Проверка включает проверку безопасности через gosec (встроенный в golangci-lint).

      Зависимости:
        - install-golangci-lint: автоматически устанавливает линтер
        - format: форматирует код перед проверкой
    deps: [ install-golangci-lint ]
    vars:
      MODULES: '{{.MODULES}}'
      GOLANGCI_LINT: '{{.GOLANGCI_LINT}}'
    cmds:
      - |
        set -e
        ERR=0
        echo "🔍 Линтим все модули ..."
        for mod in {{.MODULES}}; do
          if [ -d "$mod" ]; then
            echo "🔍 Линтим $mod module"
            {{.GOLANGCI_LINT}} run $mod/... --config=.golangci.yml || ERR=1
          fi
        done
        exit $ERR
        
    

  install-buf:
    desc: "Устанавливает Buf в каталог bin"
    cmds:
      - |
        install -d {{.BIN_DIR}} || true  # вместо mkdir -p
      - |
        [ -f {{.BUF}} ] || {
          echo '📦 Устанавливаем buf {{.BUF_VERSION}}...'
          GOBIN={{.BIN_DIR}} go install github.com/bufbuild/buf/cmd/buf@v{{.BUF_VERSION}}
        }
    status:
      - test -x {{.BUF}}

  proto:install-plugins:
      desc: "Устанавливает protoc плагины в каталог bin"
      cmds:
        - |
          [ -f {{.PROTOC_GEN_GO}} ] || {
            echo '📦 Installing protoc-gen-go...'
            GOBIN={{.BIN_DIR}} go install google.golang.org/protobuf/cmd/protoc-gen-go@{{.PROTOC_GEN_GO_VERSION}}
          }
          [ -f {{.PROTOC_GEN_GO_GRPC}} ] || {
            echo '📦 Installing protoc-gen-go-grpc...'
            GOBIN={{.BIN_DIR}} go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@{{.PROTOC_GEN_GO_GRPC_VERSION}}
          }

  proto:gen:
      deps: [ install-buf, proto:install-plugins ]
      dir: "{{.ROOT_DIR}}"
      cmds:
        - bin/buf.exe generate

  proto:lint:
      deps: [ install-buf, proto:install-plugins ]
      desc: Проверка .proto-файлов на соответствие стилю
      dir: shared/proto
      cmds:
        - '{{.BUF}} lint'

  redocly-cli:install:
    desc: Установить Redocly CLI
    cmds:
      - npm install @redocly/cli --save-dev
    status:
      - 'test -f "node_modules/.bin/redocly.cmd"'

  redocly-cli:order-v1-bundle:
    desc: "Собрать OpenAPI в один файл"
    deps: [redocly-cli:install]
    cmds:
      # Правильный порядок: bundle ФАЙЛ -o ВЫВОД
      - npx redocly bundle "{{.OPEN_API_ORDER_V1_BASE}}" -o "{{.OPEN_API_ORDER_V1_BUNDLE}}"


  ogen:gen:
    cmds:
      - .\bin\ov1.exe --target shared\pkg\api\v1 --package order --clean shared\api\bundles\order.openapi.v1.bundle.yaml


  # Генерация API кода
  gen:api:
    desc: "Генерирует Go код из OpenAPI спецификации заказа"
    cmds:
      - echo "📦 Генерация Go кода из OpenAPI спецификации..."
      # Проверяем существование файла
      - cmd: dir {{.API_BUNDLE}}
        ignore_error: true
      # Генерируем код
      - '{{.OGEN}} -target {{.API_TARGET}} -package v1 -clean {{.API_BUNDLE}}'
      - echo "✅ Генерация завершена!"
    sources:
      - '{{.API_BUNDLE}}'
    generates:
      - '{{.API_TARGET}}\*.go'



  yq:install:
    desc: "Устанавливает yq в bin/"
    cmds:
      - test -f {{.YQ}} || GOBIN={{.BIN_DIR}} go install github.com/mikefarah/yq/v4@{{.YQ_VERSION}}
    status:
      - test -f {{.YQ}}

  ogen:install:
    desc: "Скачивает ogen в папку bin"
    cmds:
      - test -f {{.OGEN}} || GOBIN={{.BIN_DIR}} go install github.com/ogen-go/ogen/cmd/ogen@{{.OGEN_VERSION}}
    status:
      - test -f {{.OGEN}}



